---
booktitle: Proceedings of the Asian Conference on Machine Learning
publisher: PMLR
volume: 25
year: '2012'
start: 2012-11-04
end: 2012-11-06
published: 2012-11-17
shortname: ACML 2012
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: BuntineACML2012
month: 0
abstract: ''
editor:
- given: Steven C. H.
  family: Hoi
- given: Wray
  family: Buntine
title: Proceedings of the Asian Conference on Machine Learning
email: ''
description: Proceedings of the Asian Conference on Machine Learning, Singapore Management
  University, Singapore
url: http://proceedings.mlr.press
baseurl: "/v25"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v25
conference:
  name: Asian Conference on Machine Learning
  url: 
  location: Singapore Management University, Singapore
  dates:
  - 2012-11-04
  - 2012-11-05
  - 2012-11-06
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v25.bib
