---
booktitle: Proceedings of the Asian Conference on Machine Learning
publisher: PMLR
volume: 25
year: '2012'
start: 2012-11-04
end: 2012-11-06
published: 2012-11-17
shortname: ACML 2012
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: BuntineACML2012
month: 0
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
cycles: false
editor:
- given: Steven C. H.
  family: Hoi
- given: Wray
  family: Buntine
description: |
  Proceedings of the Asian Conference on Machine Learning
    Held in Singapore Management University, Singapore on 04-06 November 2012

  Published as Volume 25 by the Proceedings of Machine Learning Research on 17 November 2012.

  Volume Edited by:
    Steven C. H. Hoi
    Wray Buntine

  Series Editors:
    Neil D. Lawrence
date_str: 04--06 Nov
url: http://proceedings.mlr.press
baseurl: "/v25"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v25
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Asian Conference on Machine Learning
  url: 
  location: Singapore Management University, Singapore
  dates:
  - 2012-11-04
  - 2012-11-05
  - 2012-11-06
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v25.bib
